name: CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Building release assets
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: xcode-select
      run: sudo xcode-select -s /Applications/Xcode_12.2.app

    - name: build-openssl
      run: ./build-libssh.sh
    