name: CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Building release assets
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: xcode-select
      run: sudo xcode-select -s /Applications/Xcode_12.3.app

    - name: build-openssl
      run: ./build-libssl.sh

    - name: create static xcframework
      run: ./create-openssl-framework.sh static

    - name: zip static xcframework
      run: zip -r openssl-static.xcframework.zip xcframeworks/static/openssl.xcframework  

    - name: zip libs
      run: zip -r openssl-libs.zip libs  
    
    - name: create dynamic xcframework
      run: ./create-openssl-framework.sh dynamic

    - name: zip static xcframework
      run: zip -r openssl-dynamic.xcframework.zip xcframeworks/dynamic/openssl.xcframework

    - name: zip dynamic frameworks
      run: zip -r openssl-dynamic.frameworks.zip frameworks/dynamic

    - name: zip static frameworks
      run: zip -r openssl-static.frameworks.zip frameworks/static

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset Dynamic
      id: upload-release-asset-dynamic
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./openssl-dynamic.xcframework.zip
        asset_name: openssl-dynamic.xcframework.zip
        asset_content_type: application/zip

    - name: Upload Release Asset Static
      id: upload-release-asset-static 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./openssl-static.xcframework.zip
        asset_name: openssl-static.xcframework.zip
        asset_content_type: application/zip

    - name: Upload Libs
      id: upload-release-asset-libs 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openssl-libs.zip
        asset_name: openssl-libs.zip
        asset_content_type: application/zip

    - name: Upload Dynamic Frameworks
      id: upload-release-asset-dynamic-frameworks
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./openssl-dynamic.frameworks.zip
        asset_name: openssl-dynamic.frameworks.zip
        asset_content_type: application/zip

    - name: Upload Static Frameworks
      id: upload-release-asset-static-frameworkds
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./openssl-static.frameworks.zip
        asset_name: openssl-static.frameworks.zip
        asset_content_type: application/zip